#!/system/xbin/bash

#MauNgapainGblk?

#DiRecodeGakBakalJadiinLuMastah

#DiGantiAuthorGakBakalJadiinLuMaster

#MikirMakeOtakGblk

#KontolKaloMauReedit/Recode 

#Pm Gua Bangsat

clear

cd module

python2 please.py

blue='\033[34;1m'

green='\033[32;1m' 

purple='\033[35;1m'

cyan='\033[36;1m'

red='\033[31;1m'

white='\033[37;1m' 

yellow='\033[33;1m'

sleep 1

echo $red

cat asw.txt

echo ""

echo "\033[34;1m[$]\033[36;1m============================\033[34;1m[$]"

echo "\033[32;1mAuthor : MR.KOVLAK.JR"

echo "\033[37;1mFeat: MR.DROID

echo "\033[35;1mversion Tools: New"

echo "\033[35;1mTeam : INDONESIAN SECURITY HUNTER"

echo "\033[33;1mKontak Me : 085848812535"

echo "\033[34;1m[$]\033[36;1m============================\033[34;1m[$]"

echo ""

echo "\033[32;1mWelcome To TOOL MR.KOVLAK.JR:)?:"

echo "\033[36;1m"

echo "[===============================================[>"

echo $red "1.> Spam Sms Tokopedia"

echo "[===============================================]>"

echo $white "2.> Spam Sms Telkomnyet"

echo "[===============================================]>"

echo $red "3.> Spam Sms Matahari Mall"

echo "[===============================================]>"

echo $white "4.> Spam Sms HooqTV"

echo "[===============================================]>"

echo $red "5.> Spam Sms KFC"

echo "[===============================================]>"

echo $white "6.> Spam Sms PHD"

echo "[===============================================]>"

echo $red "7.> Spam Sms Whiskas"

echo "[===============================================]>"

echo $white "8.> Spam Sms ZiPAY"

echo "[===============================================]>"

echo $red "9.> Nyari CC buat Carding"

echo "[===============================================]>"

echo $white "10.> Spam Akun Gmail"
echo "[===============================================]>"

echo $red "11.> Whois LookUp"

echo "[===============================================]>"

echo $white "12.> Upload Admin Finder"

echo "[===============================================]>"

echo $red "13.> Script Deface Creator"

echo "[===============================================]>"

echo $white "14.> ReConDog Buat Information gathering"

echo "[===============================================]>"

echo $red "15.> Admin Login Finder"

echo "[===============================================]>"

echo $white "16.> Virus VbugMaker Creator"

echo "[===============================================]>"

echo $red "17.> dowload script deface orang"

echo "[===============================================]>"

echo $white "18.> Autolike Facebook"

echo "[===============================================]>"

echo $red "19.> Facebook Auto_Reaction"

echo "[===============================================]>"

echo $white "20.> Bot Komentar Facebook"

echo "[===============================================]>"

echo $red "21.> Install txtool"

echo "[===============================================]>"

echo $white "22.> install sqlscan"

echo "[===============================================]>"

echo $red "23.> install hash-buster"

echo "[===============================================]>"

echo $white "24.> Install Red_Hawk"

echo "[===============================================]>"

echo $red "25.> Install Torshammer buat DDOS website"

echo "[===============================================]>"

echo $white "26.> Install LITEDDOS buat DDOS website"

echo "[===============================================]>"

echo $red "27.> Install Hunner Framework"

echo "[===============================================]>"

echo $white "28.> Install Sqlmap Buat Inject Situs"

echo "[===============================================]>"

echo $red "29.> Install 4wsectools"

echo "[===============================================]>"

echo $white "30.> Install Lazymux Buat Install Tools"

echo "[===============================================]>"

echo $red "31.> Mempercepat / Menstabilkan Jaringan/sinyal"

echo "[===============================================]>"

echo $white "32.> Mempercepat / menstabilkan jaringan 2"

echo "[===============================================]>"

echo $red "33.> Install BinGoo"

echo "[===============================================]>"

echo $white "34.> Full Bot Facebook"

echo "[===============================================]>"

echo $red "35.> Install Termux-A"

echo "[===============================================]>"

echo $white "36.> Install Tools GadoGado"

echo "[===============================================]>"

echo $red "37.> Install Lazysqlmap"

echo "[===============================================]>"

echo $red "38.> Install tools diejoubu"

echo "[===============================================]>"

echo $white "39.> Install weeman Buat Phising"

echo "[===============================================]>"

echo $red "40.> Install iesDEFACE buat Deface Poc Webdav"

echo "[===============================================]>"
echo $blue "0.> keluar"

echo "[+]===============================================[+]"

echo "\033[32;1m"

read -p "ISH@T00Ls-Mr.KOVLAK.Jr~#" bro


if [ $bro = 1 ] || [ $bro = 1 ]

then

clear

figlet "Mr.KOVLAK.Jr" | lolcat

php tp.php

fi


if

[ $bro = 2 ] || [ $bro = 2 ]

then

clear

toilet "Mr.KOVLAK.Jr"

php t.php

fi


if [ $bro = 3 ] || [ $bro = 3 ]

then

figlet "Mr.KOVLAK.Jr"

php mataharimall.php

fi


if [ $bro = 4 ] || [ $bro = 4 ]

then

clear

toilet "Mr.KOVLAK.Jr"

php hooq.php

fi


if [ $bro = 5 ] || [ $bro = 5 ]

then

clear

toilet -f slant --gay "Mr.KOVLAK.Jr"

php kfc.php

fi


if [ $bro = 6 ] || [ $bro = 6 ]

then

clear

toilet -f mono12 -F gay "Mr.KOVLAK.Jr"

php phd.php

fi


if [ $bro = 7 ] || [ $bro = 7 ]

then

clear

toilet "Mr.KOVLAK.Jr"

php whiskas.php

fi


if [ $bro = 8 ] || [ $bro = 8 ]

then

clear

figlet "Mr.KOVLAK.Jr"

php zipay.php

fi


if [ $bro = 9 ] || [ $bro = 9 ]

then

clear

toilet "Mr.KOVLAK.Jr"

php key.php

fi


if [ $bro = 10 ] || [ $bro = 10 ]

then

clear

toilet "Mr.KOVLAK.Jr"

python2 SpamMail.py

fi


if [ $bro = 11 ] || [ $bro = 11 ]

then

clear

toilet "Mr.KOVLAK.Jr"

python2 whs.py

fi


if [ $bro = 12 ] || [ $bro = 12 ]

then

clear

toilet "Mr.KOVLAK.Jr"

python2 upf.py

fi


if [ $bro = 13 ] || [ $bro = 13 ]

then

clear

toilet "Mr.KOVLAK.Jr"

python2 create.py

fi


if [ $bro = 14 ] || [ $bro = 14 ]

then

clear

toilet "Mr.KOVLAK.Jr"

python2 dog.py

fi


if [ $bro = 15 ] || [ $bro = 15 ]

then

clear

toilet "Mr.KOVLAK.Jr"

python2 gam.py

fi


if [ $bro = 16 ] || [ $bro = 16 ]

then

clear

toilet "Mr.KOVLAK.Jr"

python2 anvima.py

fi


if [ $bro = 17 ] || [ $bro = 17 ]

then

clear

toilet "Mr.KOVLAK.Jr"

python2 htmd.py

fi


if [ $bro = 18 ] || [ $bro = 18 ]

then

clear

toilet "Mr.KOVLAK.Jr"

php autolike.php

fi


if [ $bro = 19 ] || [ $bro = 19 ]

then

clear

toilet "Mr.KOVLAK.Jr"

python2 auto_reaction.py

fi


if [ $bro = 20 ] || [ bro = 20 ]

then

clear

figlet "Mr.KOVLAK.Jr" | lolcat

python2 botkomen.py

fi


if [ $bro = 21 ] || [ $bro = 21 ]

then

clear

figlet "Mr.KOVLAK.Jr" | lolcat

git clone https://github.com/kuburan/txtool

mv txtool $HOME

cd $HOME/txtool

python2 install.py

python2 update.py

txtool

fi



if [ $bro = 22 ] || [ bro = 22 ]

then

clear

toilet -f slant -F gay "Mr.KOVLAK.Jr" 

pkg install update && pkg install upgrade

pkg install git

pkg install php

cd module

php sqlscan.php

fi


if [ $bro = 23 ] || [ $bro = 23 ]

then

clear

toilet -f mono12 -F gay "Mr.KOVLAK.Jr" 

apt upgrade

apt install python2

apt install git

git clone https://github.com/UltimateHackers/Hash-Buster

mv Hash-Buster $HOME

cd $HOME/Hash-Buster

python2 hash.py

fi


if [ $bro = 24 ] || [ $bro = 24 ]

then

clear

toilet -f standard -F gay "Mr.KOVLAK.Jr" 

echo "\033[33;1muntuk tutorial kunjungi:" "\033[36;1m https://youtu.be/h2I5HU3W-so"

sleep 3

apt update

apt install git

apt install php

git clone https://github.com/Tuhinshubhra/RED_HAWK

mv RED_HAWK $HOME

cd $HOME/RED_HAWK

chmod +x rhawk.php

php rhawk.php

fi


if [ $bro = 25 ] || [ $bro = 25 ]

then

clear

toilet -f standard -F gay "Mr.KOVLAK.Jr" 

apt update

apt install git

apt install tor

git clone https://github.com/dotfighter/torshammer.git

mv torshammer $HOME

cd $HOME/torshammer

read -p "Masukan Target==>:" target

python2 torshammer.py -T -t target

fi


if [ $bro = 26 ] || [ $bro = 26 ]

then

clear

toilet -f standard -F gay "Mr.KOVLAK.Jr" 

echo "\033[33;1muntuk tutorial kunjungi:" "\033[36;1m https://youtu.be/EskgepQSB7U"

sleep 3

apt update

apt install git

git clone https://github.com/4L13199/LITEDDOS

mv LITEDDOS $HOME

cd $HOME/LITEDDOS

read -p "MasukanTarget:" target

python2 LITEDDOS.py target 80 100

fi


if [ $bro = 27 || [ $bro = 27 ]

then

clear

toilet -f standard -F gay "Mr.KOVLAK.Jr" 

apt update

apt install git

git clone https://github.com/b3-v3r/Hunner.git

mv Hunner $HOME

cd $HOME/Hunner

chmod +x hunner.py

python2 hunner.py

fi


if [ $bro = 28 ] || [ $bro = 28 ]

then

clear

toilet -f standard -F gay "Mr.KOVLAK.Jr"

apt update

apt install git

git clone https://github.com/sqlmapproject/sqlmap

mv sqlmap $HOME

cd $HOME/sqlmap

read -p "masukan web target:" target

python2 sqlmap.py -D target

fi


if [ $bro = 29 ] || [ $bro = 29 ]

then

clear

toilet -f standard -F gay "Mr.KOVLAK.Jr" 

apt update

apt install git

git clone https://github.com/aryanrtm/4wsectools

mv 4wsectools $HOME

cd $HOME/4wsectools

chmod 777 tools

./tools

fi


if [ $bro = 30 ] || [ $bro = 30 ]

then

clear

figlet "Mr.KOVLAK.Jr" | lolcat

apt update && upgrade

apt install python2 

apt install git

cd module

python2 lazymux.py

fi


if [ $bro = 31 ] || [ $bro = 31 ]

then

clear

figlet "Mr.KOVLAK.Jr" | lolcat

sleep 1

echo "\033[32;m====================Mempercepat / menstabilkan sinyal===================="

sleep 1

echo "\033[32;1m================================By Mr.KOVLAK.Jr================================"

sleep 1

echo ""

echo ""

ping 8.8.8.8 

fi


if [ $bro = 32 ] || [ $bro = 32 ]

then

clear

figlet "Mr.KOVLAK.Jr" | lolcat

sleep 1

echo "\033[32;m===================Mempercepat / menstabilkan sinyal 2===================="

sleep 1

echo "\033[32;1m================================By Mr.KOVLAK.Jr================================"

sleep 1

echo ""

echo ""

ping -D www.google.com

fi


if [ $bro = 33 ] || [ $bro = 33 ]

then

clear

figlet "Mr.KOVLAK.Jr" | lolcat

sleep 1

git clone https://github.com/Hood3dRob1n/BinGoo

mv BinGoo $HOME

cd $HOME/BinGoo

bash bingoo

fi


if [ $bro = 34 ] || [ $bro = 34 ]

then

clear

figlet "Mr.KOVLAK.Jr" | lolcat

sleep 1

cd module

python2 facebook.py

fi


if [ $bro = 35 ] || [ $bro = 35 ]

then

clear

figlet "Mr.KOVLAK.Jr" | lolcat

sleep 1

apt update && apt upgrade

apt install termux-api

apt install git

apt install php

git clone https://github.com/Cvar1984/Termux-A.git

mv Termux-A $HOME

cd $HOME/Termux-A

php run.php

fi


if [ $bro = 36 ] || [ $bro = 36 ]

then

clear

figlet "Mr.KOVLAK.Jr" | lolcat

sleep 1

apt update && apt upgrade

apt install ruby

apt install lolcat

apt install git

git clone https://github.com/Senitopeng/GadoGado.git

mv GadoGado $HOME

cd $HOME/GadoGado

bash gado

fi


if [ $bro = 37 ] || [ $bro = 37 ]

then

clear

figlet "Mr.KOVLAK.Jr" | lolcat

sleep 1

apt update && apt upgrade

apt install python2

apt install git

git clone https://github.com/verluchie/termux-lazysqlmap.git

mv termux-lazysqlmap $HOME

cd $HOME/termux-lazysqlmap

chmod 777 install.sh

./install.sh

lazysqlmap

fi


if [ $bro = 38 ] || [ $bro = 38 ]

then

clear

figlet "Mr.KOVLAK.Jr" | lolcat

sleep 1 

apt install git

apt install php

git clone https://github.com/alintamvanz/diejoubu

mv diejoubu $HOME

cd $HOME/diejoubu

cd v1.2

php diejoubu.php

fi


if [ $bro = 39 ] || [ $bro = 39 ]

then

clear

figlet "Mr.KOVLAK.Jr" | lolcat

sleep 1 

apt install git

apt install php

git clone https://github.com/evait-security/weeman.git

mv weeman $HOME

cd $HOME/weeman

python2 weeman.py

fi


if [ $bro = 40 ] || [ $bro = 40 ]

then

clear

figlet "Mr.KOVLAK.Jr" | lolcat

sleep 1 

apt install git

apt install bash

pip2 install bash

git clone https://github.com/ALX-04/iesDEFACE

mv iesDEFACE $HOME

cd $HOME/iesDEFACE

bash iesDeface.sh

fi

if [ $bro = 0 ] || [ $bro = 00 ]

then

echo "\033[32;1mINDONESIAN SECURITY HUNTER

sleep 1

echo "\033[33;1mWe Security"

sleep 1

echo " We Not Friends"

sleep 1

echo "We Are Family"

sleep 1

echo "Hacking Is Not Criminal;)"

sleep 1

echo "Ketika Sebuah Hayalan Tidak tercapai"

sleep 1

echo "Maka Terus lah BerJuang Dan Berusaha:)"

sleep 1

echo "\033[32;1mKarna Suatu Hari Nanti Kamu akan Mendapatkannya:)"

sleep 1

exit

fi

 
